apiVersion: v1
kind: Pod
metadata:
  name: 01-sample
spec:
  containers:
    - name: nginx
      image: nginx
#status: {


#  kubectl apply -f  01-sample.yml
#   kubectl logs 01-sample -c nginx
#   kubectl get pods -A
#   kubectl get svc -A
#  kubectl delete -f  01-sample.yml
# docker ps -A (shows containers which are failing)
# service is a load balancer in Kubernetes
# we have core dns in kubenernetes like we have dns in Amazon


