apiVersion: v1
kind: Pod
metadata:
  name: 03-service
#  labels:
#    name: 03-service
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: service-03
spec:
#  selector:
#    name: 03-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80



