#INSTRUCTION arguments
FROM      dokken/centos-8
RUN       yum install epel-release -y
RUN       yum install nginx -y
ENTRYPOINT ["nginx", "-g", "daemon off;"]
#Its like a System CTL command(entry point)



# docker build .
# docker images
# docker build -t buildname .
# docker run imageid
# docker inpsect id(container or Image)
#
#
#
#